In [1]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.4 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [2]:
!pip list

Package                      Version
---------------------------- ---------
absl-py                      1.4.0
anyio                        3.6.2
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arrow                        1.2.3
asttokens                    2.2.1
astunparse                   1.6.3
attrs                        22.2.0
backcall                     0.2.0
beautifulsoup4               4.11.2
bleach                       6.0.0
boto3                        1.26.72
botocore                     1.29.72
cachetools                   5.3.0
certifi                      2022.12.7
cffi                         1.15.1
charset-normalizer           3.0.1
comm                         0.1.2
debugpy                      1.6.6
decorator                    5.1.1
defusedxml                   0.7.1
easydict                     1.10
executing                    1.2.0
fastjsonschema               2.16.2
flatbuffers                  23.1.21
fqdn                         1.5.1
gast                         0.4.0
google-auth                  2.16.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.51.1
h5py                         3.8.0
idna                         3.4
importlib-metadata           6.0.0
ipykernel                    6.21.2
ipython                      8.10.0
ipython-genutils             0.2.0
ipywidgets                   8.0.4
isoduration                  20.11.0
jedi                         0.18.2
Jinja2                       3.1.2
jmespath                     1.0.1
jsonpointer                  2.3
jsonschema                   4.17.3
jupyter                      1.0.0
jupyter_client               8.0.2
jupyter-console              6.5.1
jupyter_core                 5.2.0
jupyter-events               0.6.3
jupyter_server               2.3.0
jupyter_server_terminals     0.4.4
jupyterlab-pygments          0.2.2
jupyterlab-widgets           3.0.5
keras                        2.11.0
libclang                     15.0.6.1
Markdown                     3.4.1
MarkupSafe                   2.1.2
matplotlib-inline            0.1.6
mistune                      2.0.5
nbclassic                    0.5.1
nbclient                     0.7.2
nbconvert                    7.2.9
nbformat                     5.7.3
nest-asyncio                 1.5.6
notebook                     6.5.2
notebook_shim                0.2.2
numpy                        1.24.2
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.0
pandas                       1.5.3
pandocfilters                1.5.0
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
pip                          23.0
platformdirs                 3.0.0
prometheus-client            0.16.0
prompt-toolkit               3.0.36
protobuf                     3.19.6
psutil                       5.9.4
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyarrow                      11.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycparser                    2.21
Pygments                     2.14.0
PyMySQL                      1.0.2
pyrsistent                   0.19.3
python-dateutil              2.8.2
python-json-logger           2.0.6
pytz                         2022.7.1
PyYAML                       6.0
pyzmq                        25.0.0
qtconsole                    5.4.0
QtPy                         2.3.0
requests                     2.28.2
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rsa                          4.9
s3transfer                   0.6.0
Send2Trash                   1.8.0
setuptools                   58.1.0
six                          1.16.0
smart-open                   6.3.0
sniffio                      1.3.0
soupsieve                    2.4
stack-data                   0.6.2
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.30.0
termcolor                    2.2.0
terminado                    0.17.1
tinycss2                     1.2.1
tornado                      6.2
traitlets                    5.9.0
typing_extensions            4.5.0
uri-template                 1.2.0
urllib3                      1.26.14
wcwidth                      0.2.6
webcolors                    1.12
webencodings                 0.5.1
websocket-client             1.5.1
Werkzeug                     2.2.3
wheel                        0.38.4
widgetsnbextension           4.0.5
wrapt                        1.14.1
zipp                         3.13.0

In [3]:
!pip freeze > requirements.txt

In [4]:
!cat requirements.txt

absl-py==1.4.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
boto3==1.26.72
botocore==1.29.72
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
comm==0.1.2
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
easydict==1.10
executing==1.2.0
fastjsonschema==2.16.2
flatbuffers==23.1.21
fqdn==1.5.1
gast==0.4.0
google-auth==2.16.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
h5py==3.8.0
idna==3.4
importlib-metadata==6.0.0
ipykernel==6.21.2
ipython==8.10.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jmespath==1.0.1
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.5.1
jupyter-events==0.6.3
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.3.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
keras==2.11.0
libclang==15.0.6.1
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib-inline==0.1.6
mistune==2.0.5
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.2
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.0.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
protobuf==3.19.6
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==11.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
PyMySQL==1.0.2
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.6
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.2
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
s3transfer==0.6.0
Send2Trash==1.8.0
six==1.16.0
smart-open==6.3.0
sniffio==1.3.0
soupsieve==2.4
stack-data==0.6.2
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.30.0
termcolor==2.2.0
terminado==0.17.1
tinycss2==1.2.1
tornado==6.2
traitlets==5.9.0
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==1.26.14
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
widgetsnbextension==4.0.5
wrapt==1.14.1
zipp==3.13.0

In [8]:
import pymysql
from easydict import EasyDict

settings = EasyDict()

settings.DB_HOST = ""
settings.DB_USER = ""
settings.DB_PASSWORD = ""
settings.DB_NAME = ""
settings.DB_PORT =

In [9]:
db = pymysql.connect(
    host = settings.DB_HOST,
    user = settings.DB_USER,
    passwd = settings.DB_PASSWORD,
    db = settings.DB_NAME,
    port = settings.DB_PORT
)
cursor = db.cursor()
cursor

In [10]:
sql = 'SELECT * FROM hotel LIMIT 10;'

result = cursor.execute(sql)
result

10

In [11]:
data = cursor.fetchall()
data

(('Resort Hotel',
  0,
  342,
  2015,
  'July',
  27,
  1,
  0,
  0,
  2,
  0.0,
  0,
  'BB',
  'PRT',
  'Direct',
  'Direct',
  0,
  0,
  0,
  'C',
  'C',
  3,
  'No Deposit',
  None,
  None,
  0,
  'Transient',
  0.0,
  0,
  0,
  'Check-Out',
  '2015-07-01'),
 ('Resort Hotel',
  0,
  737,
  2015,
  'July',
  27,
  1,
  0,
  0,
  2,
  0.0,
  0,
  'BB',
  'PRT',
  'Direct',
  'Direct',
  0,
  0,
  0,
  'C',
  'C',
  4,
  'No Deposit',
  None,
  None,
  0,
  'Transient',
  0.0,
  0,
  0,
  'Check-Out',
  '2015-07-01'),
 ('Resort Hotel',
  0,
  7,
  2015,
  'July',
  27,
  1,
  0,
  1,
  1,
  0.0,
  0,
  'BB',
  'GBR',
  'Direct',
  'Direct',
  0,
  0,
  0,
  'A',
  'C',
  0,
  'No Deposit',
  None,
  None,
  0,
  'Transient',
  75.0,
  0,
  0,
  'Check-Out',
  '2015-07-02'),
 ('Resort Hotel',
  0,
  13,
  2015,
  'July',
  27,
  1,
  0,
  1,
  1,
  0.0,
  0,
  'BB',
  'GBR',
  'Corporate',
  'Corporate',
  0,
  0,
  0,
  'A',
  'A',
  0,
  'No Deposit',
  304.0,
  None,
  0,
  'Transient',
  75.0,
  0,
  0,
  'Check-Out',
  '2015-07-02'),
 ('Resort Hotel',
  0,
  14,
  2015,
  'July',
  27,
  1,
  0,
  2,
  2,
  0.0,
  0,
  'BB',
  'GBR',
  'Online TA',
  'TA/TO',
  0,
  0,
  0,
  'A',
  'A',
  0,
  'No Deposit',
  240.0,
  None,
  0,
  'Transient',
  98.0,
  0,
  1,
  'Check-Out',
  '2015-07-03'),
 ('Resort Hotel',
  0,
  14,
  2015,
  'July',
  27,
  1,
  0,
  2,
  2,
  0.0,
  0,
  'BB',
  'GBR',
  'Online TA',
  'TA/TO',
  0,
  0,
  0,
  'A',
  'A',
  0,
  'No Deposit',
  240.0,
  None,
  0,
  'Transient',
  98.0,
  0,
  1,
  'Check-Out',
  '2015-07-03'),
 ('Resort Hotel',
  0,
  0,
  2015,
  'July',
  27,
  1,
  0,
  2,
  2,
  0.0,
  0,
  'BB',
  'PRT',
  'Direct',
  'Direct',
  0,
  0,
  0,
  'C',
  'C',
  0,
  'No Deposit',
  None,
  None,
  0,
  'Transient',
  107.0,
  0,
  0,
  'Check-Out',
  '2015-07-03'),
 ('Resort Hotel',
  0,
  9,
  2015,
  'July',
  27,
  1,
  0,
  2,
  2,
  0.0,
  0,
  'FB',
  'PRT',
  'Direct',
  'Direct',
  0,
  0,
  0,
  'C',
  'C',
  0,
  'No Deposit',
  303.0,
  None,
  0,
  'Transient',
  103.0,
  0,
  1,
  'Check-Out',
  '2015-07-03'),
 ('Resort Hotel',
  1,
  85,
  2015,
  'July',
  27,
  1,
  0,
  3,
  2,
  0.0,
  0,
  'BB',
  'PRT',
  'Online TA',
  'TA/TO',
  0,
  0,
  0,
  'A',
  'A',
  0,
  'No Deposit',
  240.0,
  None,
  0,
  'Transient',
  82.0,
  0,
  1,
  'Canceled',
  '2015-05-06'),
 ('Resort Hotel',
  1,
  75,
  2015,
  'July',
  27,
  1,
  0,
  3,
  2,
  0.0,
  0,
  'HB',
  'PRT',
  'Offline TA/TO',
  'TA/TO',
  0,
  0,
  0,
  'D',
  'D',
  0,
  'No Deposit',
  15.0,
  None,
  0,
  'Transient',
  105.5,
  0,
  0,
  'Canceled',
  '2015-04-22'))

In [12]:
for elem in data:
    print(elem)

('Resort Hotel', 0, 342, 2015, 'July', 27, 1, 0, 0, 2, 0.0, 0, 'BB', 'PRT', 'Direct', 'Direct', 0, 0, 0, 'C', 'C', 3, 'No Deposit', None, None, 0, 'Transient', 0.0, 0, 0, 'Check-Out', '2015-07-01')
('Resort Hotel', 0, 737, 2015, 'July', 27, 1, 0, 0, 2, 0.0, 0, 'BB', 'PRT', 'Direct', 'Direct', 0, 0, 0, 'C', 'C', 4, 'No Deposit', None, None, 0, 'Transient', 0.0, 0, 0, 'Check-Out', '2015-07-01')
('Resort Hotel', 0, 7, 2015, 'July', 27, 1, 0, 1, 1, 0.0, 0, 'BB', 'GBR', 'Direct', 'Direct', 0, 0, 0, 'A', 'C', 0, 'No Deposit', None, None, 0, 'Transient', 75.0, 0, 0, 'Check-Out', '2015-07-02')
('Resort Hotel', 0, 13, 2015, 'July', 27, 1, 0, 1, 1, 0.0, 0, 'BB', 'GBR', 'Corporate', 'Corporate', 0, 0, 0, 'A', 'A', 0, 'No Deposit', 304.0, None, 0, 'Transient', 75.0, 0, 0, 'Check-Out', '2015-07-02')
('Resort Hotel', 0, 14, 2015, 'July', 27, 1, 0, 2, 2, 0.0, 0, 'BB', 'GBR', 'Online TA', 'TA/TO', 0, 0, 0, 'A', 'A', 0, 'No Deposit', 240.0, None, 0, 'Transient', 98.0, 0, 1, 'Check-Out', '2015-07-03')
('Resort Hotel', 0, 14, 2015, 'July', 27, 1, 0, 2, 2, 0.0, 0, 'BB', 'GBR', 'Online TA', 'TA/TO', 0, 0, 0, 'A', 'A', 0, 'No Deposit', 240.0, None, 0, 'Transient', 98.0, 0, 1, 'Check-Out', '2015-07-03')
('Resort Hotel', 0, 0, 2015, 'July', 27, 1, 0, 2, 2, 0.0, 0, 'BB', 'PRT', 'Direct', 'Direct', 0, 0, 0, 'C', 'C', 0, 'No Deposit', None, None, 0, 'Transient', 107.0, 0, 0, 'Check-Out', '2015-07-03')
('Resort Hotel', 0, 9, 2015, 'July', 27, 1, 0, 2, 2, 0.0, 0, 'FB', 'PRT', 'Direct', 'Direct', 0, 0, 0, 'C', 'C', 0, 'No Deposit', 303.0, None, 0, 'Transient', 103.0, 0, 1, 'Check-Out', '2015-07-03')
('Resort Hotel', 1, 85, 2015, 'July', 27, 1, 0, 3, 2, 0.0, 0, 'BB', 'PRT', 'Online TA', 'TA/TO', 0, 0, 0, 'A', 'A', 0, 'No Deposit', 240.0, None, 0, 'Transient', 82.0, 0, 1, 'Canceled', '2015-05-06')
('Resort Hotel', 1, 75, 2015, 'July', 27, 1, 0, 3, 2, 0.0, 0, 'HB', 'PRT', 'Offline TA/TO', 'TA/TO', 0, 0, 0, 'D', 'D', 0, 'No Deposit', 15.0, None, 0, 'Transient', 105.5, 0, 0, 'Canceled', '2015-04-22')

In [13]:
cursor.description

(('hotel', 252, None, 262140, 262140, 0, True),
 ('is_canceled', 8, None, 20, 20, 0, True),
 ('lead_time', 8, None, 20, 20, 0, True),
 ('arrival_date_year', 8, None, 20, 20, 0, True),
 ('arrival_date_month', 252, None, 262140, 262140, 0, True),
 ('arrival_date_week_number', 8, None, 20, 20, 0, True),
 ('arrival_date_day_of_month', 8, None, 20, 20, 0, True),
 ('stays_in_weekend_nights', 8, None, 20, 20, 0, True),
 ('stays_in_week_nights', 8, None, 20, 20, 0, True),
 ('adults', 8, None, 20, 20, 0, True),
 ('children', 5, None, 22, 22, 31, True),
 ('babies', 8, None, 20, 20, 0, True),
 ('meal', 252, None, 262140, 262140, 0, True),
 ('country', 252, None, 262140, 262140, 0, True),
 ('market_segment', 252, None, 262140, 262140, 0, True),
 ('distribution_channel', 252, None, 262140, 262140, 0, True),
 ('is_repeated_guest', 8, None, 20, 20, 0, True),
 ('previous_cancellations', 8, None, 20, 20, 0, True),
 ('previous_bookings_not_canceled', 8, None, 20, 20, 0, True),
 ('reserved_room_type', 252, None, 262140, 262140, 0, True),
 ('assigned_room_type', 252, None, 262140, 262140, 0, True),
 ('booking_changes', 8, None, 20, 20, 0, True),
 ('deposit_type', 252, None, 262140, 262140, 0, True),
 ('agent', 5, None, 22, 22, 31, True),
 ('company', 5, None, 22, 22, 31, True),
 ('days_in_waiting_list', 8, None, 20, 20, 0, True),
 ('customer_type', 252, None, 262140, 262140, 0, True),
 ('adr', 5, None, 22, 22, 31, True),
 ('required_car_parking_spaces', 8, None, 20, 20, 0, True),
 ('total_of_special_requests', 8, None, 20, 20, 0, True),
 ('reservation_status', 252, None, 262140, 262140, 0, True),
 ('reservation_status_date', 252, None, 262140, 262140, 0, True))

In [15]:
columns = [elem[0] for elem in cursor.description]

In [16]:
import pandas as pd

df = pd.DataFrame(data, columns = columns)

In [17]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,None,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,None,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,None,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,None,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,None,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,None,0,Transient,105.5,0,0,Canceled,2015-04-22

In [18]:
def get_query(sql: str):
    cursor.execute(sql)
    
    data = cursor.fetchall()
    columns = [elem[0] for elem in cursor.description]
    
    return pd.DataFrame(data, columns = columns)

In [21]:
sql = 'SELECT * FROM hotel LIMIT 12;'

df = get_query(sql)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,None,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,None,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,None,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,None,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,None,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,None,0,Transient,105.5,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,None,0,Transient,123.0,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,None,0,Transient,145.0,0,0,Check-Out,2015-07-05

In [24]:
sql = "SELECT * FROM hotel WHERE arrival_date_year = 2015 && arrival_date_month = 'July';"

df = get_query(sql)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2771,City Hotel,0,1,2015,July,31,30,0,1,1,...,No Deposit,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-31
2772,City Hotel,0,210,2015,July,31,30,0,1,2,...,No Deposit,9.0,NaN,0,Transient-Party,76.50,0,0,Check-Out,2015-07-31
2773,City Hotel,0,1,2015,July,31,30,0,1,1,...,No Deposit,NaN,NaN,0,Transient,0.00,0,1,Check-Out,2015-07-31
2774,City Hotel,0,209,2015,July,31,29,1,4,1,...,No Deposit,7.0,NaN,0,Transient,55.96,0,0,Check-Out,2015-08-03
2775,City Hotel,0,210,2015,July,31,30,1,3,1,...,No Deposit,9.0,NaN,0,Transient-Party,68.00,0,0,Check-Out,2015-08-03